[package]
name = "nezuo/data-store-service-mock"
version = "0.3.9"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
realm = "shared"

[dependencies]
